---
- name: Converge
  hosts: prdx-nfs14.ziyotek4.local
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: /home/ansible/project-team4/project-team4/nfs/geerlingguy.nfs
